first_proj:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 17 for SQL Server' # (The ODBC Driver installed on your system)
      server: LAPTOP-HMF8Q5ET\SQLEXPRESS
      port: 1433
      windows_login: true
      database: Enterprise
      schema: dbo
      trust_cert: true